### ISSUE TITLE
What is cname for?

### ISSUE THREAD

**Issue by sampadap03** [wwosimulation/wolvesville#2]
@thewilloftheshadow

**Comment by thewilloftheshadow** [comment]
That was how I use the custom domain to work for the site. I do it a different way now though. https://wovsim.theshadow.xyz

**Comment by sampadap03** [comment]
yeah but it is already hosted on github.io; it only increase the load on your host, which is not necessary I suggest.

**Comment by thewilloftheshadow** [comment]
No its not running on my host, it just forwards to github.io

**Comment by sampadap03** [comment]
okay
